---
- name: Postgresql-pg | install pg
  include_tasks: install_pg.yml
  when:
    - install_database
- name: Postgresql-etcd | reset pg
  include_tasks: reset_pg.yml
  when:
    - uninstall_database or reset_pg