---
## 非使用客户提供的NFS服务场景时
- name: NFS-reset | Remove file
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ nfs_dir }}"
    - /etc/exports
  when: not nfs_exist

- name: NFS-reset | Stop rpcbind service
  service:
    name: rpcbind
    state: stopped
  failed_when: false
  when: not nfs_exist

- name: NFS-reset | Stop nfs-server service
  service:
    name: nfs-server
    state: stopped
  failed_when: false
  when: not nfs_exist

- name: NFS | Create nfs directory if they don't exist
  file:
    path: "{{ nfs_dir }}"
    state: directory
    mode: 0775
  when: nfs_exist

## 使用客户提供的NFS服务场景时
- name: NFS | Mount nfs directory
  mount:
    src: "{{ remote_nfs_server }}:{{ remote_nfs_path }}"
    path: "{{ nfs_dir }}"
    state: mounted
    fstype: nfs
  when: nfs_exist

- name: NFS | Delete tianyu directory if they don't exist
  file:
    path: "{{ nfs_dir }}/{{ item }}"
    state: absent
  with_items:
    - "{{ tianyu_dir }}"
  when: nfs_exist

- name: NFS | Delete repo directory if they don't exist
  file:
    path: "{{ nfs_dir }}/{{ item }}"
    state: absent
  with_items:
    - "{{ repo_dir }}"
  when: nfs_exist

#- name: create repo file path
#  shell: mkdir -p {{ nfs_dir }}/{{item}}
#  with_items: [ psql/psql-data-0 psql/psql-data-1 psql/psql-data-2 krmp/dynflow-data krmp/repo-data krmp/repo-conf ]
- name: NFS | Delete softshop directory if they don't exist
  file:
    path: "{{ nfs_dir }}/{{ item }}"
    state: absent
  with_items:
    - "{{ softshop_dir }}"
  when: nfs_exist

- name: NFS | Unmount nfs directory
  mount:
    src: "{{ remote_nfs_server }}:{{ remote_nfs_path }}"
    path: "{{ nfs_dir }}"
    state: unmounted
    fstype: nfs
  when: nfs_exist

- name: NFS | Delete template nfs directory
  file:
    path: "{{ nfs_dir }}"
    state: absent
  when: nfs_exist