---
- name: Postgresql-keepalived | install keepalived
  include_tasks: install_keepalived.yml
  when:
    - install_database
- name: Postgresql-keepalived | reset keepalived
  include_tasks: reset_keepalived.yml
  when:
    - uninstall_database or reset_keepalived